# Site settings
title: Tomas Jay
author: Tomas Jay
description: "Rantings and musings of Tomas Jay"
baseurl: ""
url: "https://tomaswerts.com"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-113168316-1
google_tag_manager:

# Optional features
show_related_posts: True
show_subscribe_cta: True
show_social_icons: True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: tomaskjay
linkedin_username: tomas-jay
spotify_username: 3inmn1rnjtruxm39f1rbs65zc?si=9uWm0yBjTDGNKnxGdAyfkA&nd=1&dlsi=285748dc646d4104

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
paginate: 12
paginate_path: "/blog/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude: [vendor]

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true
